import '@cloudscape-design/global-styles/index.css';
import ContentLayout from '@cloudscape-design/components/content-layout';
import Header from '@cloudscape-design/components/header';
import SpaceBetween from '@cloudscape-design/components/space-between';

import Head from 'next/head';
import TransformationPlayground from './TransformationPlayground';

export default function Home() {
  return (
    <>
      <Head>
        <title>Migration Assistant Transformation Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ContentLayout
          defaultPadding
          header={
            <SpaceBetween size="m">
              <Header variant="h1">Transformation Playground</Header>
            </SpaceBetween>
          }
        >
          <TransformationPlayground />
        </ContentLayout>
      </main>
    </>
  );
}
