name: E2E Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Generate Cache Key from Dockerfiles
        id: generate_cache_key
        run: |
          files=$(find . -type f \( -name 'docker-compose.yml' -o -name 'Dockerfile' \))
          key=$($(cat $files) | sha1sum | awk '{print $1}')
          echo "key=${key}" >> "$GITHUB_OUTPUT"

      - name: Cache Docker Images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ steps.generate_cache_key.outputs.key }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.0.2
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Start Docker Solution
        run: ../gradlew dockerSolution:ComposeUp -x test --scan --info --stacktrace
        working-directory: TrafficCapture
        env:
          OS_MIGRATIONS_GRADLE_SCAN_TOS_AGREE_AND_ENABLED: ''

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd test
          python -m pip install --upgrade pip
          pip install -r requirements.txt 


      - name: Run E2E test script
        run: |
          cd test
          chmod +x ./tests.py
          #pytest tests.py --unique_id="testindex"
